language: csharp
solution: CovidOutApp.sln
install:
  - nuget restore CovidOutApp.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CovidOutApp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./CovidOutApp.Tests/bin/Release/CovidOutApp.Tests.dll