language: csharp
dist: trusty
mono: none
dotnet: 3.1.300
install:
- dotnet restore
script:
- dotnet build CovidOutApp.Web/CovidOutApp.Web.csproj
- dotnet test CovidOutApp.Tests/CovidOutApp.Tests.csproj